### ISSUE TITLE
symfony 2.7 deprecated messages.

### ISSUE THREAD

**Issue by feyyazesat** [boekkooi/JqueryValidationBundle#27]
Hi,
Recently I upgraded my application to sf 2.7 and I'm getting following deprecated messages from debug toolbar, it is a small issue, Before upgrade The original function was "sameas", and "same as" created for an alias but now "same as" is the original and "sameas" deprecated documentation says, so any update shouldn't be break backward compability.

DEPRECATED - Twig Test "sameas" is deprecated. Use "same as" instead in BoekkooiJqueryValidationBundle:Form:macros.js.twig at line 53.
DEPRECATED - Twig Test "sameas" is deprecated. Use "same as" instead in BoekkooiJqueryValidationBundle:Form:conditions.js.twig at line 2.
DEPRECATED - Twig Test "sameas" is deprecated. Use "same as" instead in BoekkooiJqueryValidationBundle:Form:conditions.js.twig at line 9.
DEPRECATED - Twig Test "sameas" is deprecated. Use "same as" instead in BoekkooiJqueryValidationBundle:Form:conditions.js.twig at line 27.

**Comment by boekkooi** [comment]
Thanks for the report. 

The reason that `sameas` is still used is because the lowest twig dependency is `1.12.2` and `same as` was introduced in `1.14.2` A simple fix you be to update the twig dependency and update the code. I would be ok with releasing this as a new minor version.

Could you create a PR for this?

**Comment by feyyazesat** [comment]
Sure I'll take care of this. I'll send PR ASAP.
