### ISSUE TITLE
Should checkbox with constraint IsTrue work out of the box?

### ISSUE THREAD

**Issue by robertfausk** [boekkooi/JqueryValidationBundle#30]
...or do I have to implement the constraint IsTrue by myself? I'm trying to use type checkbox with IsTrue validator to force user to check the terms.

http://symfony.com/doc/current/reference/constraints/IsTrue.html

In jquery validation doc I didn't find that it's supported: http://jqueryvalidation.org/documentation/#link-list-of-built-in-validation-methods
and in additional-methods.js there is no IsTrue method.

**Comment by boekkooi** [comment]
Hi @robertfausk,

Currently the IsTrue constraint is not supported (my bad). I will take a look at this as soon as I have time and see how the constraint/rule can be best implemented. 

Thank you for reporting!

**Comment by robertfausk** [comment]
Shall I create issues for further missing constraints/rules?
I could also send you some PR (if it's not to hard to implement them ;) )

**Comment by boekkooi** [comment]
@robertfausk The issue sounds like a good idea! 

Well the IsTrue implementation is a little complex because there are some constraints for the IsTrue constraint. For example given that a field is a checkbox then IsTrue means that the checkbox is required but if the field is a choice then the value must be matched to the true value.

So the IsTrue constraint mapper is a combination of the [required rule](https://github.com/boekkooi/JqueryValidationBundle/blob/master/src/Form/Rule/Mapping/RequiredRule.php) and the [equalTo rule](http://jqueryvalidation.org/equalTo-method). 

If you have the time to make a PR this would be great! but if not I can pick it up somewhere this or next week.

**Comment by boekkooi** [comment]
The IsTrue and IsFalse rules have been added they are part of the additional methods.
Please try dev-master :smile:

**Comment by robertfausk** [comment]
Tried! And works! Thank you.
