### ISSUE TITLE
[Feature] [Twig extension] allow to render only rules without js code.

### ISSUE THREAD

**Issue by aitboudad** [boekkooi/JqueryValidationBundle#6]
```
{{ form(form, { attr: 'data-rules': form_jquery_validation_rules()  }) }}
```

**Comment by boekkooi** [comment]
Hi @aitboudad, Thanks for the request it is a interesting idea. Can you maybe explain a little more about why you would like this feature?

I mean a `data-rule-<rule>` and `data-msg-<rule>` could be added to the FormView attrs but to my knowledge this approach won't work when you have a field that has a `depends` option or a if `validation_groups` are used.

**Comment by aitboudad** [comment]
Hi,
I mean the function ```form_jquery_validation_rules``` will generate only an array of rules without extra js code, the main idea is to avoid calling ```form_jquery_validation(form)``` for each form.
Below an example of what would like to do:

```jinja
{# app/Resources/views/Form/fields.html.twig #}
{% block form_start -%}
    ...
    {% set attr = attr|merge({'data-rules': form_jquery_validation_rules(form) }) %}
{%- endblock form_start %}
```
```js
// main.js
$('form').each(function() {
    var rules = $(this).data('rules');
    $(this).validate({
      rules: rules
    });
});
```

**Comment by boekkooi** [comment]
To my regret I don't see this as a possibility. The main reason for this is that to support form [`validation_groups`](http://symfony.com/doc/current/book/forms.html#validation-groups) the [`depends` ](http://jqueryvalidation.org/validate#rules) rule option is used and a custom `validation_groups` setting. 

I don't really see a disadvantage of having the JavaScript part in a `<script>` tag in the page (but maybe I'm missing something). 
If the reason is that you want to ensure that you have the JavaScript at the end of the HTML then you could use [TwigJackBundle defer](https://github.com/boekkooi/TwigJackBundle/blob/master/doc/twig-defer.md).

I can imagine that you want to only use the `rules` and not the `messages` set on the validator. If this is the case adding a argument to `form_jquery_validation` would solve this, or you can override [`BoekkooiJqueryValidationBundle:Form:form_validate.js.twig`](https://github.com/boekkooi/JqueryValidationBundle/blob/master/src/Resources/views/Form/form_validate.js.twig).

**Comment by aitboudad** [comment]
Thanks I used the last one.
